account/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = "account"

urlpatterns = [
    path('loginRegister/', views.loginRegister, name='loginRegister'),
    # 登录注册页
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='logout'),
    # 注销
    path('forgetPassword/', views.forgetPassword, name='forgetPassword'),
    # 忘记密码

    path('', views.account, name='account'),
    # 个人中心模块
    path('personalCenter/', views.personalCenter, name='personalCenter'),
    # 个人中心首页
    path('changeInformation/', views.changeInformation, name='changeInformation'),
    # 修改信息
    path('changePassword/', views.changePassword, name='changePassword'),
    # 修改密码
    path('changeEmail/', views.changeEmail, name='changeEmail'),
    # 修改邮箱
    path('historyBrowse/', views.historyBrowse, name='historyBrowse'),
    # 浏览记录
    path('historyLike/', views.historyLike, name='historyLike'),
    # 收藏记录
    path('historyComment/', views.historyComment, name='historyComment'),
    # 评论记录
    path('historyLeave/', views.historyLeave, name='historyLeave'),
    # 留言记录

    path('tableData', views.tableData, name='tableData'),
    # ajax动态表格数据
    path('tableSearch', views.tableSearch, name='tableSearch'),
    # ajax动态表格搜索
    path('tableForm', views.tableForm, name='tableForm'),
    # ajax动态表格表单

    path('registerCheck', views.registerCheck, name='registerCheck'),
    # ajax用户注册信息验证
    path('imageUpload/', views.imageUpload, name='imageUpload'),
    # ajax图片上传接口(头像 文章封面)
    path('commentUpload/', views.commentUpload, name='commentUpload'),
    # ajax评论图片上传
    path('markdownUpload/', views.markdownUpload, name='markdownUpload'),
    # ajax markdown图片上传
    path('emailCode/', views.emailCode, name='emailCode'),
    # ajax获取邮件验证码
    path('checkEmailCode/', views.checkEmailCode, name='checkEmailCode'),
    # ajax校验邮件验证码
    path('bindEmail/', views.bindEmail, name='bindEmail'),
    # ajax绑定邮箱
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('category-<int:category_id>/', views.category, name='category'),
    # 文章分类列表
    path('tag-<int:tag_id>/', views.tag, name='tag'),
    # 文章标签列表
    path('note-<int:note_id>/', views.note, name='note'),
    # 学习笔记
    path('show-<int:article_id>/', views.show, name='show'),
    # 文章内容页
    path('section-<int:content_id>/', views.section, name='section'),
    # 笔记内容页
    path('timeAxis/', views.timeAxis, name='timeAxis'),
    # 时间轴
    path('messageBoard/', views.messageBoard, name='messageBoard'),
    # 留言板
    path('about/', views.about, name='about'),
    # 关于
    path('link/', views.link, name='link'),
    # 友情链接
    path('search', views.search, name='search'),
    # 搜索
    path('initApi', views.initApi, name='initApi'),
    # 初始化数据接口

    path('categoryPage', views.categoryPage, name='categoryPage'),
    # ajax文章分类分页
    path('tagPage', views.tagPage, name='tagPage'),
    # ajax标签分类分页
    path('indexPage', views.indexPage, name='indexPage'),
    # ajax首页流加载
    path('articleLike', views.articleLike, name='articleLike'),
    # ajax文章点赞
    path('articleCollection', views.articleCollection, name='articleCollection'),
    # ajax文章添加收藏
    path('deleteCollection', views.deleteCollection, name='deleteCollection'),
    # ajax文章取消收藏
    path('timeArticle', views.timeArticle, name='timeArticle'),
    # ajax时间轴文章列表
    path('postMessage', views.postMessage, name='postMessage'),
    # ajax发布留言
    path('likeMessage', views.likeMessage, name='likeMessage'),
    # ajax点赞留言
    path('delMessage', views.delMessage, name='delMessage'),
    # ajax删除留言
    path('postComment', views.postComment, name='postComment'),
    # ajax发布评论
    path('likeComment', views.likeComment, name='likeComment'),
    # ajax点赞评论
    path('delComment', views.delComment, name='delComment'),
    # ajax删除评论
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from blog import views
from django.views.static import serve
from myblog.settings import MEDIA_ROOT

urlpatterns = [
    re_path('media/(?P<path>.*)', serve, {'document_root': MEDIA_ROOT}, name='media_url'),
    # 媒体资源
    path('', views.index, name='index'),
    # 博客首页
    path('myblog_admin/', admin.site.urls),
    # admin管理页
    path('login/', include('social_django.urls', namespace='social')),
    # 第三方账户登录
    path('account/', include('account.urls', namespace='account')),
    # 个人中心
    path('blog/', include('blog.urls', namespace='blog')),
    # 博客前台
    path('management/', include('management.urls', namespace='management')),
    # 博客后台
    path('captcha', include('captcha.urls')),
    # 验证码
    path('sitemap/', views.siteMap, name='siteMap'),
    # 生成网站地图
]

account/views.py
import json
import random


import requests
from django.contrib.auth.models import User
from captcha.helpers import captcha_image_url
from captcha.models import CaptchaStore
from django.contrib.auth import authenticate, login
from django.contrib.auth.backends import ModelBackend
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from social_django.models import UserSocialAuth
from django.core.paginator import Paginator
from django.db.models import Q
from django.forms import model_to_dict
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.utils import timezone
from PIL import Image
from account.forms import *
from account.models import UserInfo, ArticleViewHistory, CommentMessage, LeaveMessage, SectionMessage, \
    SectionViewHistory
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.decorators.clickjacking import xframe_options_sameorigin
from django.views.decorators.csrf import csrf_exempt

from blog.models import Article, Category, Tag, Note, Section, Catalogue
from management.models import Carousel, Link, ImagesConfig
from PIL import Image as ImagePIL, ImageFont, ImageDraw

# 设置邮箱、用户名都可以登录
from management.tools import sendEmail


class CustomBackend(ModelBackend):
    def authenticate(self, request, username=None, password=None, **kwargs):
        try:
            user = User.objects.get(Q(username=username) | Q(email=username))
            if user.check_password(password):
                return user
        except Exception as e:
            print(e)
            return None


# 登录注册页
def loginRegister(request):
    if request.method == "POST":
        type = request.POST.get('type')
        if type == "登录":
            login_form = LoginForm(request.POST)
            # 创建一个对象，获得post方法提交的数据
            if login_form.is_valid():
                # 验证传入的数据是否合法
                login_data = login_form.cleaned_data
                # 引入字典数据类型，存储用户名和密码
                user = authenticate(username=login_data['user'], password=login_data['password'])
                # 验证账号密码是否正确，正确返回user对象，错误返回null
                if user:
                    # 调用django默认的login方法，实现用户登录
                    login(request, user)
                    # 登录后跳转的页面
                    next_url = request.GET.get("next")
                    if next_url:
                        print(next_url)
                        return HttpResponseRedirect(next_url)
                    else:
                        return HttpResponseRedirect('/')
                else:
                    message = '用户名或密码错误！'
                    hashkey = CaptchaStore.generate_key()
                    image_url = captcha_image_url(hashkey)
                    login_form = LoginForm()
                    register_form = RegisterForm()
                    print(message)
                    return render(request, "account/loginRegister.html", locals())
            else:
                message = '验证码错误！'
                hashkey = CaptchaStore.generate_key()
                image_url = captcha_image_url(hashkey)
                login_form = LoginForm()
                register_form = RegisterForm()
                print(message)
                return render(request, "account/loginRegister.html", locals())
        elif type == "注册":
            register_form = RegisterForm(request.POST)
            # 创建一个对象，获得post方法提交的数据
            if register_form.is_valid():
                register_data = register_form.cleaned_data
                # 校验邮件验证码
                try:
                    session_code = request.session['email_code']
                except KeyError:
                    data = {
                        "code": 0,
                        "msg": "邮件验证码已过期！"
                    }
                    return JsonResponse(data)
                if register_data['email_code'] != session_code:
                    data = {
                        "code": 0,
                        "msg": "邮件验证码错误！"
                    }
                    return JsonResponse(data)
                # 校验通过，创建用户
                username = register_data['username']
                password = register_data['password1']
                email = register_data['email']
                new_user = User.objects.create()
                new_user.username = username
                new_user.set_password(password)
                new_user.email = email
                new_user.save()
                # 创建用户信息表记录
                UserInfo.objects.create(user_id=new_user.id)
                # 创建完用户自动登录
                user = authenticate(username=username, password=password)
                # 调用django默认的login方法，实现用户登录
                login(request, user)
                data = {
                    "code": 1,
                    "msg": "注册成功，自动跳转至首页并登陆！"
                }
                return JsonResponse(data)
            else:
                ErrorDict = register_form.errors
                print(ErrorDict)
                data = {
                    "code": 0,
                    "msg": "请求数据异常！"
                }
                return JsonResponse(data)

    else:
        hashkey = CaptchaStore.generate_key()
        image_url = captcha_image_url(hashkey)
        login_form = LoginForm()
        register_form = RegisterForm()
        return render(request, 'account/loginRegister.html', locals())


# 忘记密码
def forgetPassword(request):
    if request.method == "POST":
        forget_form = ForgetForm(request.POST)
        if forget_form.is_valid():
            forget_data = forget_form.cleaned_data
            email = forget_data['email']
            password = forget_data['password1']
            user = User.objects.get(email=email)
            user.set_password(password)
            user.save()
            data = {
                "code": 1,
                "msg": "密码重置成功！"
            }
            return JsonResponse(data)
        else:
            ErrorDict = forget_form.errors
            print(ErrorDict)
            data = {
                "code": 0,
                "msg": "请求数据异常！"
            }
            return JsonResponse(data)

    else:
        forget_form = ForgetForm()
        return render(request, 'account/forgetPassword.html', locals())


# 个人中心模块
@login_required()
def account(request):
    try:
        userinfo = UserInfo.objects.get(user_id=request.user.id)
    except Exception as e:
        print(e)
        userinfo = None
    return render(request, 'layui-mini/base.html', locals())


# 第三方用户头像下载至本地
def downloadPhoto(url):
    # url='http://thirdqq.qlogo.cn/g?b=oidb&k=TGX7Iu5wFlTiasg1VOiaeYMA&s=40&t=1598856813'
    filename = "%s.%s" % (timezone.now().strftime('%Y_%m_%d_%H_%M_%S_%f'), "jpg")
    filepath = 'media/photo/' + filename
    db_path = 'photo/' + filename
    html = requests.get(url)
    with open(filepath, 'wb') as file:
        file.write(html.content)
    file.close()
    return db_path


# 个人中心首页
@login_required()
@xframe_options_exempt
def personalCenter(request):
    try:
        userinfo = UserInfo.objects.get(user_id=request.user.id)
        # print("注册用户登录")
    except Exception as e:
        # 第三方用户
        print(e)
        "第三方用户第一次登录"
        social_user = UserSocialAuth.objects.get(user_id=request.user.id)
        if social_user.provider == 'github':
            # print("github登录")
            UserInfo.objects.create(user_id=request.user.id)
            user = User.objects.get(id=request.user.id)
        else:
            # print("qq 微博登录")
            username = social_user.extra_data['username'].replace(" ", "")
            photo_url = social_user.extra_data['profile_image_url']
            username = social_user.extra_data['username'].replace(" ", "")
            photo_url = social_user.extra_data['profile_image_url']
            sex = social_user.extra_data['gender']
            # print(sex)
            if sex == '女' or sex == 'f':
                sex_id = 2
            else:
                sex_id = 1
            user_info = UserInfo()
            user_info.user_id = request.user.id
            user_info.photo = downloadPhoto(photo_url)
            user_info.sex = sex_id
            user_info.save()
            new_user = User.objects.get(id=request.user.id)
            new_user.username = username
            new_user.save()
            user = new_user
    article_view = ArticleViewHistory.objects.filter(user=request.user).count()
    article_like = ArticleViewHistory.objects.filter(user=request.user).filter(is_like=1).count()
    article_comment = CommentMessage.objects.filter(user=request.user).count()
    section_view = SectionViewHistory.objects.filter(user=request.user).count()
    section_like = SectionViewHistory.objects.filter(user=request.user).filter(is_like=1).count()
    section_comment = SectionMessage.objects.filter(user=request.user).count()
    leave_count = LeaveMessage.objects.filter(user=request.user).count()
    return render(request, 'layui-mini/account/index.html', locals())


# 修改密码
@login_required()
@xframe_options_exempt
def changePassword(request):
    if request.method == "POST":
        change_password_form = ChangePasswordForm(request.POST)
        if change_password_form.is_valid():
            change_password_data = change_password_form.cleaned_data
            old_password = change_password_data['password_old']
            new_password = change_password_data['password1']
            user = authenticate(username=request.user.username, password=old_password)
            # 验证账号密码是否正确，正确返回user对象，错误返回null
            if user:
                user.set_password(new_password)
                user.save()
                return HttpResponseRedirect(reverse('account:logout'))
            else:
                message = "原始密码错误！"
        else:
            message = "表单数据异常！"
        change_password_form = ChangePasswordForm()

templates/layui-mini/account/bindEmail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>绑定邮箱</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'layui-mini/lib/layui-v2.5.5/css/layui.css' %}" media="all">
    <link rel="stylesheet" href="{% static 'layui-mini/css/public.css' %}" media="all">
</head>
<body>
<div class="layuimini-container">
    <div class="layuimini-main">
        <form class="layui-form" action="{% url 'account:changeEmail' %}" method="post">
            {% csrf_token %}
            <div class="layui-card-body">
                <div class="layui-form-item">
                    <label class="layui-form-label">邮箱号</label>
                    <div class="layui-input-inline">
                        <input type="text" name="title" lay-verify="title" autocomplete="off" placeholder="请输入邮箱号"
                               class="layui-input">
                    </div>
                    <button type="button" class="layui-btn layui-btn-normal" id="send_btn">发送验证码</button>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">验证码</label>
                    <div class="layui-input-inline">
                        <input type="text" name="title" lay-verify="title" autocomplete="off" placeholder="请输入验证码"
                               class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <div class="layui-input-block">
                        <button type="submit" class="layui-btn" lay-submit="">提交</button>
                        <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script src="{% static 'layui-mini/lib/layui-v2.5.5/layui.js' %}" charset="utf-8"></script>
<script>
    layui.use(['form'], function () {
        var form = layui.form
            , layer = layui.layer
            , $ = layui.jquery;
        // 提示信息
        var message = '{{ message }}';
        if (message) {
            layer.alert(message, {icon: 2})
        }
        // ajax加载动画
        var load
        $(document).on('ajaxStart', function () {
            load = layer.load();
        })
        $(document).on('ajaxComplete', function () {
            layer.close(load);
        })
        // 发送邮件验证码
        $("#send_btn").click(function () {
            var email = $("input[ name='email' ]").val();
            if (email.length == 0) {
                layer.msg("请输入邮箱号", {icon: 2})
                return false;
            }
            var enoughRegex = new RegExp("[\\w!#$%&'*+/=?^_`{|}~-]+(?:\\.[\\w!#$%&'*+/=?^_`{|}~-]+)*@(?:[\\w](?:[\\w-]*[\\w])?\\.)+[\\w](?:[\\w-]*[\\w])?", "g");
            if (enoughRegex.test(email) == false) {
                layer.msg("请输入正确的邮箱号", {icon: 2})
                return false;
            }
            if ($("#send_btn").hasClass("layui-btn-disabled")) {
                layer.msg("验证码已发送，请稍后再试", {icon: 2})
                return false;
            }
            if (email_repeat(email)) {
                layer.msg("该邮箱号已被绑定！", {icon: 2})
                return false;
            }
            $.ajax({
                type: "GET",
                url: "{% url 'account:emailCode' %}",
                data: {
                    email: email,
                    action: "更换邮箱",
                    username: "{{ user.username }}",
                },
                success: function (result) {
                    if (result.code == 1) {
                        layer.msg(result.msg, {icon: 1});
                        $("#send_btn").addClass("layui-btn-disabled");     //控制按钮为禁用
                        var second = 60;
                        var intervalObj = setInterval(function () {
                            $("#send_btn").text("重新获取" + "(" + second + ")");
                            if (second == 0) {
                                $("#send_btn").text("获取验证码");
                                $("#send_btn").removeClass("layui-btn-disabled");//将按钮可用
                                /* 清除已设置的setInterval对象 */
                                clearInterval(intervalObj);
                            }
                            second--;
                        }, 1000);
                    } else {
                        layer.alert(result.msg, {icon: 2});
                    }
                },
                error: function (xhr) {
                    alert(xhr.text());
                }
            })
        });

        // ajax验证邮箱号存在
        function email_repeat(value) {
            var repeat = false;
            $.ajax({
                type: "GET",
                url: "{% url 'account:registerCheck' %}",
                async: false,
                data: {email: value},
                success: function (result) {
                    if (result.code == 0) {
                        repeat = true;
                    }
                },
                error: function (xhr) {
                    alert(xhr.text());
                }
            })
            return repeat;
        }
    });
</script>
</body>
</html>

templates/layui-mini/account/changeInformation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改信息</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'layui-mini/lib/layui-v2.5.5/css/layui.css' %}" media="all">
    <link rel="stylesheet" href="{% static 'layui-mini/css/public.css' %}" media="all">
</head>
<body>
<div class="layuimini-container">
    <div class="layuimini-main">
        <form class="layui-form" action="." method="post">
            {% csrf_token %}
            <div class="layui-form-item">
                <label class="layui-form-label">用户名：</label>
                <div class="layui-input-inline">
                    {{ user_form.username }}
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">邮箱：</label>
                <div class="layui-input-inline">
                    {{ user_form.email }}
                </div>
                <div class="layui-word-aux" id="change-email">
                    <a href="#" class="layui-btn layui-btn-normal">修改邮箱</a>
                </div>
            </div>

            <div class="layui-form-item">
                <label class="layui-form-label">性别：</label>
                <div class="layui-input-block">
                    {{ userinfo_form.sex }}
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">手机号：</label>
                <div class="layui-input-inline">
                    {{ userinfo_form.phone }}
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">头像：</label>
                <div class="layui-input-inline layui-btn-container photo-change">
                    <img src="{{ MEDIA_URL }}{{ userinfo.photo }}" id="photo-img" width="150px" height="150px">
                    <button type="button" class="layui-btn layui-btn-normal" id="editimg">修改头像</button>
                    <tip>点击图片查看大图，图片分辨率：150*150</tip>
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">个人站点：</label>
                <div class="layui-input-inline">
                    {{ userinfo_form.web }}
                </div>
                <div class="layui-form-mid layui-word-aux">完整url地址，如https://www.baidu.com/</div>
            </div>
            <div class="layui-form-item layui-form-text">
                <label class="layui-form-label">个性签名：</label>
                <div class="layui-input-block">
                    {{ userinfo_form.aboutme }}
                </div>
            </div>
            <div class="layui-form-item">
                <div class="layui-input-block">
                    <button class="layui-btn" lay-submit="" lay-filter="setmyinfo">确认修改</button>
                    <button type="reset" class="layui-btn layui-btn-primary">重新填写</button>
                </div>
            </div>
        </form>
    </div>
</div>
<script src="{% static 'jquery-3.5.1/jquery-3.5.1.min.js' %}" charset="utf-8"></script>
<script src="{% static 'js/csrf.js' %}" charset="utf-8"></script>
<script src="{% static 'layui-mini/lib/layui-v2.5.5/layui.js' %}" charset="utf-8"></script>
<script src="{% static 'layui-mini/js/lay-config.js' %}" charset="utf-8"></script>
<script>
    layui.use(['form', 'layedit', 'laydate', 'croppers', 'miniTab'], function () {
        var form = layui.form
            , layer = layui.layer
            , $ = layui.jquery
            , croppers = layui.croppers
            , miniTab = layui.miniTab;
        // 点击修改邮箱跳转
        $("#change-email a").click(function () {
            // 打开新的窗口
            miniTab.openNewTabByIframe({
                href: "/account/changeEmail",
                title: "修改邮箱",
            });
        })

        // ajax验证用户名存在
        function username_repeat(value) {
            var repeat = false;
            $.ajax({
                type: "GET",
                url: "{% url 'account:registerCheck' %}",
                async: false,
                data: {username: value},
                success: function (result) {
                    if (result.code == 0) {
                        repeat = true;
                    }
                },
                error: function (xhr) {
                    alert(xhr.text());
                }
            })
            return repeat;
        }

        // 用户名验证
        var check_name = '{{ request.user.username }}'
        form.verify({
            username: function (value) {
                if (check_name != value) {
                    var ze = /^[\S]{3,8}$/;
                    if (!ze.test(value)) {
                        return '用户名长度为3到8位';
                    }
                    if (username_repeat(value)) {
                        return '用户名已存在！'
                    }
                }
            }
        });
        // 错误提示信息
        if ('{{ message }}') {
            layer.msg('{{ message }}')
        }
        // 设置裁剪图片
        var open_height;
        w = $(window).width(); //浏览器当前窗口可视区域宽度
        if (w > 768) {
            open_height = '70%'
        } else {
            open_height = '100%'
        }
        //创建一个头像上传组件
        croppers.render({
            elem: '#editimg'
            , saveW: 150     //保存宽度
            , saveH: 150
            , mark: 1 / 1    //选取比例
            , area: open_height  //弹窗宽度
            , url: "{% url "account:imageUpload" %}"  //图片上传接口返回和（layui 的upload 模块）返回的JOSN一样
            , data: {type: 'photo'}
            , done: function (src) { //上传完毕回调
                layer.msg("上传成功！", {icon: 6});
                $("#photo-img").attr('src', src);
                $(".layui-nav-img").attr('src', src);
            }
        });
        // 表单提交
        form.on('submit(setmyinfo)', function (data) {
            var formdata = $('form').serialize()
            var data = formdata + '&photo=' + $("#photo-img").attr('src')
            $.ajax({
                type: "POST",
                url: "{% url 'account:changeInformation' %}",
                data: data,
                success: function (result) {
                    if (result.code == 1) {
                        layer.msg(result.msg, {icon: 6});
                        setTimeout(function () {
                            miniTab.deleteCurrentByIframe();
                        }, 1000); // 延时5秒
                    } else {
                        layer.alert(result.msg, {icon: 2});
                    }
                },
                error: function (xhr) {
                    alert(xhr.text());
                }
            })
            return false; //阻止表单跳转。如果需要表单跳转，去掉这段即可。
        });
        // 图片点击放大
        $('.photo-change img').on('click', function () {
            layer.photos({
                photos: '.photo-change',
                closeBtn: 2,
                anim: 0
            });
        })
    })
</script>
</body>
</html>

templates/layui-mini/account/changePassword.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改密码</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'layui-mini/lib/layui-v2.5.5/css/layui.css' %}" media="all">
    <link rel="stylesheet" href="{% static 'layui-mini/css/public.css' %}" media="all">
</head>
<body>
<div class="layuimini-container">
    <div class="layuimini-main">
        <form class="layui-form" action="{% url 'account:changePassword' %}" method="post">
            {% csrf_token %}
            <div class="layui-card-body" pad15="">
                {% for change_password in change_password_form %}
                    <div class="layui-form-item">
                        <label class="layui-form-label">{{ change_password.label_tag }}</label>
                        <div class="layui-input-inline">
                            {{ change_password }}
                        </div>
                    </div>
                {% endfor %}
                <div class="layui-form-item">
                    <div class="layui-input-block">
                        <button type="submit" class="layui-btn" lay-submit="">提交</button>
                        <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script src="{% static 'layui-mini/lib/layui-v2.5.5/layui.js' %}" charset="utf-8"></script>
<script>
    layui.use(['form'], function () {
        var form = layui.form
            , layer = layui.layer;
        //自定义验证规则
        form.verify({
            password: [
                /^(?![a-zA-z]+$)(?!\d+$)(?![!@#$%^&*]+$)[a-zA-Z\d!@#$%^&*]{6,20}$/
                , '密码必须6到20位，数字加字母组合！'
            ],
            password_same: function () {
                var password1 = $("input[ name='password1' ]").val()
                var password2 = $("input[ name='password2' ]").val()
                if (password1 != password2) {
                    return '密码不一致！'
                }
            }
        });

        // 提示信息
        var message = '{{ message }}';
        if (message) {
            layer.alert(message, {icon: 2})
        }

    });
</script>
</body>
</html>