account/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = "account"

urlpatterns = [
    path('loginRegister/', views.loginRegister, name='loginRegister'),
    # 登录注册页
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='logout'),
    # 注销
    path('forgetPassword/', views.forgetPassword, name='forgetPassword'),
    # 忘记密码

    path('', views.account, name='account'),
    # 个人中心模块
    path('personalCenter/', views.personalCenter, name='personalCenter'),
    # 个人中心首页
    path('changeInformation/', views.changeInformation, name='changeInformation'),
    # 修改信息
    path('changePassword/', views.changePassword, name='changePassword'),
    # 修改密码
    path('changeEmail/', views.changeEmail, name='changeEmail'),
    # 修改邮箱
    path('historyBrowse/', views.historyBrowse, name='historyBrowse'),
    # 浏览记录
    path('historyLike/', views.historyLike, name='historyLike'),
    # 收藏记录
    path('historyComment/', views.historyComment, name='historyComment'),
    # 评论记录
    path('historyLeave/', views.historyLeave, name='historyLeave'),
    # 留言记录

    path('tableData', views.tableData, name='tableData'),
    # ajax动态表格数据
    path('tableSearch', views.tableSearch, name='tableSearch'),
    # ajax动态表格搜索
    path('tableForm', views.tableForm, name='tableForm'),
    # ajax动态表格表单

    path('registerCheck', views.registerCheck, name='registerCheck'),
    # ajax用户注册信息验证
    path('imageUpload/', views.imageUpload, name='imageUpload'),
    # ajax图片上传接口(头像 文章封面)
    path('commentUpload/', views.commentUpload, name='commentUpload'),
    # ajax评论图片上传
    path('markdownUpload/', views.markdownUpload, name='markdownUpload'),
    # ajax markdown图片上传
    path('emailCode/', views.emailCode, name='emailCode'),
    # ajax获取邮件验证码
    path('checkEmailCode/', views.checkEmailCode, name='checkEmailCode'),
    # ajax校验邮件验证码
    path('bindEmail/', views.bindEmail, name='bindEmail'),
    # ajax绑定邮箱
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('category-<int:category_id>/', views.category, name='category'),
    # 文章分类列表
    path('tag-<int:tag_id>/', views.tag, name='tag'),
    # 文章标签列表
    path('note-<int:note_id>/', views.note, name='note'),
    # 学习笔记
    path('show-<int:article_id>/', views.show, name='show'),
    # 文章内容页
    path('section-<int:content_id>/', views.section, name='section'),
    # 笔记内容页
    path('timeAxis/', views.timeAxis, name='timeAxis'),
    # 时间轴
    path('messageBoard/', views.messageBoard, name='messageBoard'),
    # 留言板
    path('about/', views.about, name='about'),
    # 关于
    path('link/', views.link, name='link'),
    # 友情链接
    path('search', views.search, name='search'),
    # 搜索
    path('initApi', views.initApi, name='initApi'),
    # 初始化数据接口

    path('categoryPage', views.categoryPage, name='categoryPage'),
    # ajax文章分类分页
    path('tagPage', views.tagPage, name='tagPage'),
    # ajax标签分类分页
    path('indexPage', views.indexPage, name='indexPage'),
    # ajax首页流加载
    path('articleLike', views.articleLike, name='articleLike'),
    # ajax文章点赞
    path('articleCollection', views.articleCollection, name='articleCollection'),
    # ajax文章添加收藏
    path('deleteCollection', views.deleteCollection, name='deleteCollection'),
    # ajax文章取消收藏
    path('timeArticle', views.timeArticle, name='timeArticle'),
    # ajax时间轴文章列表
    path('postMessage', views.postMessage, name='postMessage'),
    # ajax发布留言
    path('likeMessage', views.likeMessage, name='likeMessage'),
    # ajax点赞留言
    path('delMessage', views.delMessage, name='delMessage'),
    # ajax删除留言
    path('postComment', views.postComment, name='postComment'),
    # ajax发布评论
    path('likeComment', views.likeComment, name='likeComment'),
    # ajax点赞评论
    path('delComment', views.delComment, name='delComment'),
    # ajax删除评论
]

management/urls.py
from django.urls import path
from . import views

app_name = "management"

urlpatterns = [
    path('', views.management, name='management'),
    # 后台管理模块
    path('dashboard/', views.dashboard, name='dashboard'),
    # 后台管理dashboard
    path('articleAdd/', views.articleAdd, name='articleAdd'),
    # 新增文章
    path('articleList/', views.articleList, name='articleList'),
    # 文章列表
    path('articleCategory/', views.articleCategory, name='articleCategory'),
    # 文章分类
    path('articleTag/', views.articleTag, name='articleTag'),
    # 文章标签
    path('articleComment/', views.articleComment, name='articleComment'),
    # 文章评论
    path('sectionNote/', views.sectionNote, name='sectionNote'),
    # 笔记名称
    path('sectionList/', views.sectionList, name='sectionList'),
    # 笔记列表
    path('sectionAdd/', views.sectionAdd, name='sectionAdd'),
    # 新增笔记内容
    path('sectionComment/', views.sectionComment, name='sectionComment'),
    # 笔记评论
    path('sectionCatalog/', views.sectionCatalog, name='sectionCatalog'),
    # 笔记目录编排
    path('websiteLeaveMessage/', views.websiteLeaveMessage, name='websiteLeaveMessage'),
    # 网站留言
    path('websiteCarousel/', views.websiteCarousel, name='websiteCarousel'),
    # 网站轮播图
    path('carouselAdd/', views.carouselAdd, name='carouselAdd'),
    # 新增轮播图
    path('websiteLink/', views.websiteLink, name='websiteLink'),
    # 网站友情链接
    path('linkAdd/', views.linkAdd, name='linkAdd'),
    # 新增友情链接
    path('websiteAbout/', views.websiteAbout, name='websiteAbout'),
    # 网站关于
    path('websiteConfig/', views.websiteConfig, name='websiteConfig'),
    # 网站配置
    path('BloggerInfo/', views.BloggerInfo, name='BloggerInfo'),
    # 博主信息
    path('managementUser/', views.managementUser, name='managementUser'),
    # 用户管理

    path('coverUpload/', views.coverUpload, name='coverUpload'),
    # ajax文章封面图片上传
    path('articleDel/', views.articleDel, name='articleDel'),
    # ajax删除文章
    path('articleEdit-<int:article_id>/', views.articleEdit, name='articleEdit'),
    # ajax修改文章
    path('categoryDel/', views.categoryDel, name='categoryDel'),
    # ajax删除分类
    path('categoryEdit/', views.categoryEdit, name='categoryEdit'),
    # ajax修改分类
    path('categoryAdd/', views.categoryAdd, name='categoryAdd'),
    # ajax新增分类
    path('tagAdd/', views.tagAdd, name='tagAdd'),
    # ajax新增标签
    path('tagEdit/', views.tagEdit, name='tagEdit'),
    # ajax修改标签
    path('tagDel/', views.tagDel, name='tagDel'),
    # ajax删除标签
    path('noteAdd/', views.noteAdd, name='noteAdd'),
    # ajax新增笔记名称
    path('noteDel/', views.noteDel, name='noteDel'),
    # ajax删除笔记名称
    path('noteEdit/', views.noteEdit, name='noteEdit'),
    # ajax修改笔记名称
    path('sectionDel/', views.sectionDel, name='sectionDel'),
    # ajax删除笔记内容
    path('sectionEdit-<int:section_id>/', views.sectionEdit, name='sectionEdit'),
    # ajax修改笔记内容
    path('catalogEdit/', views.catalogEdit, name='catalogEdit'),
    # ajax获取章节名称
    path('carouselDel/', views.carouselDel, name='carouselDel'),
    # ajax删除轮播图
    path('carouselEdit-<int:carousel_id>/', views.carouselEdit, name='carouselEdit'),
    # ajax编辑轮播图
    path('linkDel/', views.linkDel, name='linkDel'),
    # ajax删除友链
    path('linkEdit-<int:link_id>/', views.linkEdit, name='carouselEdit'),
    # ajax编辑友链
    path('userDel/', views.userDel, name='userDel'),
    # ajax删除用户
    path('echartsData', views.echartsData, name='echartsData'),
    # ajax echarts数据接口
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from blog import views
from django.views.static import serve
from myblog.settings import MEDIA_ROOT

urlpatterns = [
    re_path('media/(?P<path>.*)', serve, {'document_root': MEDIA_ROOT}, name='media_url'),
    # 媒体资源
    path('', views.index, name='index'),
    # 博客首页
    path('myblog_admin/', admin.site.urls),
    # admin管理页
    path('login/', include('social_django.urls', namespace='social')),
    # 第三方账户登录
    path('account/', include('account.urls', namespace='account')),
    # 个人中心
    path('blog/', include('blog.urls', namespace='blog')),
    # 博客前台
    path('management/', include('management.urls', namespace='management')),
    # 博客后台
    path('captcha', include('captcha.urls')),
    # 验证码
    path('sitemap/', views.siteMap, name='siteMap'),
    # 生成网站地图
]

management/models.py
from django.db import models

# Create your models here.


from mdeditor.fields import MDTextField


# 轮播图
class Carousel(models.Model):
    img = models.ImageField('轮播图', upload_to='carousel/')
    url = models.URLField('图片链接', max_length=300)
    info = models.CharField('图片标题', max_length=50, default='')
    is_show = models.BooleanField('是否显示', default=True)

    def __str__(self):
        return self.info

    class Meta:
        verbose_name = '轮播图管理'
        verbose_name_plural = '轮播图管理'


# 友情链接
class Link(models.Model):
    logo = models.ImageField('网站图标', upload_to='logo/')
    name = models.CharField('链接名称', max_length=20)
    url = models.URLField('网址', max_length=100)
    describe = models.CharField('图片标题', max_length=100, default='')
    type_choice = [('1', '友情链接'), ('2', '强烈推荐')]
    type = models.CharField(verbose_name='类型', max_length=1, choices=type_choice, default=1)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = '友情链接'


# 关于
class About(models.Model):
    body = MDTextField()
    time = models.DateTimeField('更新时间', auto_now=True)

    class Meta:
        verbose_name = '关于页面'
        verbose_name_plural = '关于页面'


# 网站配置
class WebsiteConfig(models.Model):
    name = models.CharField('网站名称', max_length=20)
    domain = models.URLField('网站域名', max_length=50)
    index_title = models.CharField('首页标题', max_length=50)
    keywords = models.CharField('META关键词', max_length=200, blank=True, null=True)
    descript = models.CharField('META描述', max_length=300, blank=True, null=True)
    copyright = models.CharField('版权信息', max_length=100)

    class Meta:
        verbose_name = '网站配置'
        verbose_name_plural = '网站配置'


# 图片配置
class ImagesConfig(models.Model):
    foreground = models.ImageField(upload_to='images/', verbose_name='前台logo', default='images/logo_forground.png')
    background = models.ImageField(upload_to='images/', verbose_name='后台logo', default='images/logo_background.png')
    icon = models.ImageField(upload_to='images/', verbose_name='icon', default='images/favicon.ico')
    photo = models.ImageField(upload_to='images/', verbose_name='默认头像', default='images/photo.jpg')
    cover = models.ImageField(upload_to='images/', verbose_name='默认封面', default='images/cover.jpg')
    pay = models.ImageField(upload_to='images/', verbose_name='赞赏二维码', default='images/pay.png')

    class Meta:
        verbose_name = '图片配置'
        verbose_name_plural = '图片配置'


# 博主信息
class Info(models.Model):
    position = models.CharField('职位', max_length=10)
    company = models.CharField('单位', max_length=20)
    location = models.CharField('地址', max_length=10)
    email = models.EmailField('邮箱', max_length=50)
    csdn = models.URLField('CSDN', max_length=50)
    github = models.URLField('GitHub', max_length=50)
    qq = models.ImageField(upload_to='images/', verbose_name='qq二维码', default='images/qq.png')
    weixin = models.ImageField(upload_to='images/', verbose_name='微信二维码', default='images/weixin.png')

    class Meta:
        verbose_name = '博主信息'
        verbose_name_plural = '博主信息'

templates/layui-mini/management/articleTag.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>文章标签</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="{% static 'layui-mini/lib/layui-v2.5.5/css/layui.css' %}" media="all">
    <link rel="stylesheet" href="{% static 'layui-mini/css/public.css' %}" media="all">
</head>
<body>
<div class="layuimini-container">
    <div class="layuimini-main">
        <fieldset class="table-search-fieldset">
            <legend>搜索信息</legend>
            <div class="layui-form layui-form-pane">
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">标签名称</label>
                        <div class="layui-input-inline">
                            <input type="text" name="tag" autocomplete="off" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-inline">
                        <button type="submit" class="layui-btn layui-btn-primary" lay-submit
                                lay-filter="data-search-btn"><i class="layui-icon"></i> 搜 索
                        </button>
                    </div>
                </div>
            </div>
        </fieldset>
        <script type="text/html" id="toolbar">
            <div class="layui-btn-container">
                <button class="layui-btn layui-btn-normal layui-btn-sm data-add-btn" lay-event="add">添加</button>
                <button class="layui-btn layui-btn-sm layui-btn-danger data-delete-btn" lay-event="delete">删除</button>
            </div>
        </script>
        <table class="layui-hide" id="currentTable" lay-filter="currentTableFilter"></table>
        <script type="text/html" id="TableBar">
            <a class="layui-btn layui-btn-xs data-count-view" lay-event="view">
                <i class="layui-icon layui-icon-read"></i>查看</a>
            <a class="layui-btn layui-btn-normal layui-btn-xs data-count-edit" lay-event="edit">
                <i class="layui-icon layui-icon-edit"></i>编辑</a>
            <a class="layui-btn layui-btn-xs layui-btn-danger data-count-delete" lay-event="delete">
                <i class="layui-icon layui-icon-delete"></i>删除</a>
        </script>

    </div>
</div>
<script src="{% static 'layui-mini/lib/layui-v2.5.5/layui.js' %}" charset="utf-8"></script>
<script src="{% static 'layui-mini/js/lay-config.js' %}" charset="utf-8"></script>
<script src="{% static 'layui-mini/js/lay-module/layuimini/miniTab.js' %}" charset="utf-8"></script>
<script src="{% static 'jquery-3.5.1/jquery-3.5.1.min.js' %}" charset="utf-8"></script>
<script src="{% static 'js/csrf.js' %}" charset="utf-8"></script>
<script>
    // 打开新窗口
    function open_win(url) {
        window.open(url);
    }
</script>
<script>
    layui.use(['form', 'table', 'laydate', 'miniTab'], function () {
        var $ = layui.jquery,
            form = layui.form,
            table = layui.table,
            miniTab = layui.miniTab;
        // 初始化表格
        table.render({
            elem: '#currentTable',
            url: "{% url 'account:tableData' %}?type=article_tag",//数据接口,
            toolbar: '#toolbar',
            defaultToolbar: ['filter', 'exports', 'print'],
            title: '文章列表',
            cols: [[ //表头
                {type: 'checkbox', fixed: 'left'}
                , {field: 'id', title: 'ID', sort: true, fixed: 'left'}
                , {field: 'name', title: '标签名称'}
                , {field: 'article_count', title: '文章数', sort: true}
                , {title: '操作', toolbar: '#TableBar'}
            ]],
            initSort: {
                field: 'article_count' //排序字段，对应 cols 设定的各字段名
                , type: 'desc' //排序方式  asc: 升序、desc: 降序、null: 默认排序
            },
            limits: [10, 15, 20, 25, 50, 100],
            limit: 15,
            page: true,
            even: true
        });

        // 监听搜索操作
        form.on('submit(data-search-btn)', function (data) {
            var result = JSON.stringify(data.field);
            var search_len = 0
            Object.keys(data.field).forEach(function (key) {
                search_len = search_len + data.field[key].length
            })
            if (search_len == 0) {
                layer.msg("请输入搜索条件！", {icon: 2})
                return false;
            }
            var data = 'type=tag_name&tag=' + data.field.tag
            var url = '/account/tableSearch?' + data
            console.log(url)
            //执行表格数据重载
            table.reload('currentTable', {
                url: url
                , where: {
                    searchParams: result
                }
            }, 'data');
        });

        // 头工具栏事件
        table.on('toolbar(currentTableFilter)', function (obj) {
            if (obj.event === 'add') {
                // 监听添加操作
                var index = layer.open({
                    title: '添加标签',
                    type: 1,
                    shade: 0.2,
                    shadeClose: true,
                    content: '<div class="collection-box-div">\n' +
                        '    <div class="collection-text">\n' +
                        '        请输入新文章标签名:\n' +
                        '    </div>\n' +
                        '    <div class="layui-input-inline">\n' +
                        '        <input type="text" name="tagname" lay-verify="required" lay-reqtext="请填写文章标签名"\n' +
                        '               autocomplete="off" class="layui-input">\n' +
                        '    </div>\n' +
                        '</div>',
                    btn: ['确定', '取消'],
                    btnAlign: 'c',
                    yes: function () {
                        var tagname = $('input[name="tagname"]').val()
                        $.ajax({
                            type: "POST",
                            url: "{% url 'management:tagAdd' %}",
                            data: {
                                name: tagname,
                            },
                            success: function (result) {
                                if (result.code == 1) {
                                    layer.msg(result.msg, {icon: 6});
                                    //执行表格数据重载
                                    var data = 'type=article_tag'
                                    var url = '/account/tableData?' + data
                                    table.reload('currentTable', {
                                        url: url
                                        , where: {
                                            searchParams: result
                                        }
                                    }, 'data');
                                } else {
                                    layer.alert(result.msg, {icon: 2});
                                }
                            },
                            error: function (xhr) {
                                alert(xhr.text());
                            }
                        })
                        layer.closeAll();
                    },
                    btn2: function () {
                        layer.closeAll();
                    }
                });
            } else if (obj.event === 'delete') {
                // 监听删除操作
                var checkStatus = table.checkStatus('currentTable')
                    , data = checkStatus.data;
                layer.confirm('确定要删除吗？', function (index) {
                    var delidArr = []
                    data.forEach(function (array) {
                        delidArr.push(array.id)
                    })
                    $.ajax({
                        type: "GET",
                        url: "{% url 'management:tagDel' %}",
                        data: {
                            delidArr: delidArr.toString(),
                        },
                        success: function (result) {
                            if (result.code == 1) {
                                layer.msg(result.msg, {icon: 6});
                                //执行表格数据重载
                                var data = 'type=article_tag'
                                var url = '/account/tableData?' + data
                                table.reload('currentTable', {
                                    url: url
                                    , where: {
                                        searchParams: result
                                    }
                                }, 'data');
                            } else {
                                layer.alert(result.msg, {icon: 2});
                            }
                        },
                        error: function (xhr) {
                            alert(xhr.text());
                        }
                    })
                    layer.closeAll();
                })
            }
        });

        //监听表格复选框选择
        table.on('checkbox(currentTableFilter)', function (obj) {
            console.log(obj)
        });

        // 监听行工具事件
        table.on('tool(currentTableFilter)', function (obj) {
            if (obj.event === 'edit') {
                // 修改标签名
                var index = layer.open({
                    title: '修改标签名',
                    type: 1,
                    shade: 0.2,
                    shadeClose: true,
                    content: '<div class="collection-box-div">\n' +
                        '    <div class="collection-text">\n' +
                        '        请输入新文章标签名:\n' +
                        '    </div>\n' +
                        '    <div class="layui-input-inline">\n' +
                        '        <input type="text" name="tagname" lay-verify="required" lay-reqtext="请填写文章标签名"\n' +
                        '               autocomplete="off" class="layui-input"> ' +
                        '    </div>\n' +
                        '</div>',
                    btn: ['确定', '取消'],
                    btnAlign: 'c',
                    yes: function () {
                        var tagname = $('input[name="tagname"]').val()
                        $.ajax({
                            type: "POST",
                            url: "{% url 'management:tagEdit' %}",
                            data: {
                                tag_id: obj.data.id,
                                name: tagname
                            },
                            success: function (result) {
                                if (result.code == 1) {
                                    layer.msg(result.msg, {icon: 6});
                                    layer.closeAll();
                                    //执行表格数据重载
                                    var data = 'type=article_tag'
                                    var url = '/account/tableData?' + data
                                    table.reload('currentTable', {
                                        url: url
                                        , where: {
                                            searchParams: result
                                        }
                                    }, 'data');
                                } else {
                                    layer.msg(result.msg, {icon: 2});
                                    layer.closeAll();
                                }
                            },
                            error: function (xhr) {
                                alert(xhr.text());
                            }
                        })
                    },
                    btn2: function () {
                        layer.closeAll();
                    }
                });
            } else if (obj.event === 'delete') {
                // 删除标签
                layer.confirm('确定要删除吗？', function (index) {
                    $.ajax({
                        type: "GET",
                        url: "{% url 'management:tagDel' %}",
                        data: {del_id: obj.data.id},
                        success: function (result) {
                            if (result.code == 1) {
                                layer.msg(result.msg, {icon: 6});
                                setTimeout(function () {
                                    layer.closeAll();
                                }, 2000);
                                //执行表格数据重载
                                var data = 'type=article_tag'
                                var url = '/account/tableData?' + data
                                table.reload('currentTable', {
                                    url: url
                                    , where: {
                                        searchParams: result
                                    }
                                }, 'data');
                            } else {
                                layer.msg(result.msg, {icon: 2});
                                layer.closeAll();
                            }
                        },
                        error: function (xhr) {
                            alert(xhr.text());
                        }
                    })
                });
            } else if (obj.event === 'view') {
                // 查看标签
                var url = '/blog/tag-' + obj.data.id
                open_win(url)
            }
        });
    });
</script>
</body>
</html>

templates/layui-mini/management/sectionEdit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>笔记内容修改</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'layui-mini/lib/layui-v2.5.5/css/layui.css' %}" media="all">
    <link rel="stylesheet" href="{% static 'layui-mini/css/public.css' %}" media="all">
    <link rel="stylesheet" href="{% static 'editormd/css/editormd.css' %}">
</head>
<body>


<div class="cintent-card">
    <form class="layui-form">
        <div class="layui-form-item">
            <label class="layui-form-label">笔记标题：</label>
            <div class="layui-input-block">
                <input type="text" name="edit-title" lay-verify="required" lay-reqtext="请填写笔记标题"
                       placeholder="请输入笔记标题"
                       class="layui-input" value={{ section.title }}>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">所属笔记：</label>
            <div class="layui-input-block">
                <select id="which_note" name="note_id" lay-filter="which_note">
                    {% for note in note_all %}
                        {% if note.id == section.note_id %}
                            <option value={{ note.id }} selected="">{{ note.name }}</option>
                        {% else %}
                            <option value={{ note.id }}>{{ note.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">所属章节：</label>
            <div class="layui-input-block">
                <select id="which_father" name="father_id">
                </select>
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">笔记内容：</label>
            <div class="layui-input-block" id="input-textarea">
                <div id="test-editor">
                    <textarea style="display:none;">{{ section.body }}</textarea>
                </div>
            </div>
        </div>
    </form>
</div>
<script src="{% static 'jquery-3.5.1/jquery-3.5.1.min.js' %}" charset="utf-8"></script>
<script src="{% static 'js/csrf.js' %}" charset="utf-8"></script>
<script src="{% static 'layui-mini/lib/layui-v2.5.5/layui.js' %}" charset="utf-8"></script>
<script src="{% static 'layui-mini/js/lay-config.js' %}" charset="utf-8"></script>
<script src="{% static 'editormd/editormd.js' %}" charset="utf-8"></script>
<script>
    // markdown编辑器
    var editor = editormd("test-editor", {
        width: "100%",
        height: "800px",
        path: "{% static 'editormd/lib/' %}",
        emoji: true, // 开启表情的功能！ 图片的本地配置！
        tex: true,                   // 开启科学公式TeX语言支持，默认关闭
        flowChart: true,             // 开启流程图支持，默认关闭
        sequenceDiagram: true,       // 开启时序/序列图支持，默认关闭,
        imageUpload: true,           // 本地图片上传，默认关闭
        imageFormats: ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
        imageUploadURL: "{% url 'account:markdownUpload' %}",
    });

    // 子页面提交笔记方法
    function sectionEdit(type) {
        var code
        $.ajax({
            type: "POST",
            url: '/management/sectionEdit-' + {{section.id}} +'/',
            async: false,
            data: {
                id: {{ section.id }},
                title: $(" input[ name='edit-title' ] ").val(),
                note_id: $("#which_note").val(),
                father_id: $("#which_father").val(),
                content: editor.getMarkdown(),
                type: type,
            },
            success: function (result) {
                if (result.code == 1) {
                    layer.msg(result.msg, {icon: 6});
                    code = 1;
                } else {
                    layer.alert(result.msg, {icon: 2});
                    code = 0;
                }
            },
            error: function (xhr) {
                alert(xhr.text());
            }
        })
        return code;
    }

    layui.use(['form', 'croppers'], function () {
        var $ = layui.jquery,
            form = layui.form,
            layer = layui.layer;

        // 加载章节
        function loadFather(note_id) {
            $.ajax({
                type: "GET",
                url: "{% url 'management:catalogEdit' %}",
                data: {
                    note_id: note_id,
                },
                success: function (result) {
                    if (result.code == 1) {
                        layer.msg(result.msg, {icon: 6});
                        console.log(result.father)
                        $("#which_father").empty();
                        $.each(result.father, function (i, val) {
                            var $option = '<option value="' + val.id + '">' + val.name + '</option>'
                            $("#which_father").append($option)
                            form.render('select');
                        })
                    } else {
                        layer.alert(result.msg, {icon: 2});
                    }
                },
                error: function (xhr) {
                    alert(xhr.text());
                }
            })
        }

        // 初始化章节
        var load_id = $("#which_note").val()
        loadFather(load_id)

        // 切换笔记
        form.on('select(which_note)', function (data) {
            var select_id = data.value
            loadFather(select_id)
        });
    });
</script>
</body>
</html>