account/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = "account"

urlpatterns = [
    path('loginRegister/', views.loginRegister, name='loginRegister'),
    # 登录注册页
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='logout'),
    # 注销
    path('forgetPassword/', views.forgetPassword, name='forgetPassword'),
    # 忘记密码

    path('', views.account, name='account'),
    # 个人中心模块
    path('personalCenter/', views.personalCenter, name='personalCenter'),
    # 个人中心首页
    path('changeInformation/', views.changeInformation, name='changeInformation'),
    # 修改信息
    path('changePassword/', views.changePassword, name='changePassword'),
    # 修改密码
    path('changeEmail/', views.changeEmail, name='changeEmail'),
    # 修改邮箱
    path('historyBrowse/', views.historyBrowse, name='historyBrowse'),
    # 浏览记录
    path('historyLike/', views.historyLike, name='historyLike'),
    # 收藏记录
    path('historyComment/', views.historyComment, name='historyComment'),
    # 评论记录
    path('historyLeave/', views.historyLeave, name='historyLeave'),
    # 留言记录

    path('tableData', views.tableData, name='tableData'),
    # ajax动态表格数据
    path('tableSearch', views.tableSearch, name='tableSearch'),
    # ajax动态表格搜索
    path('tableForm', views.tableForm, name='tableForm'),
    # ajax动态表格表单

    path('registerCheck', views.registerCheck, name='registerCheck'),
    # ajax用户注册信息验证
    path('imageUpload/', views.imageUpload, name='imageUpload'),
    # ajax图片上传接口(头像 文章封面)
    path('commentUpload/', views.commentUpload, name='commentUpload'),
    # ajax评论图片上传
    path('markdownUpload/', views.markdownUpload, name='markdownUpload'),
    # ajax markdown图片上传
    path('emailCode/', views.emailCode, name='emailCode'),
    # ajax获取邮件验证码
    path('checkEmailCode/', views.checkEmailCode, name='checkEmailCode'),
    # ajax校验邮件验证码
    path('bindEmail/', views.bindEmail, name='bindEmail'),
    # ajax绑定邮箱
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('category-<int:category_id>/', views.category, name='category'),
    # 文章分类列表
    path('tag-<int:tag_id>/', views.tag, name='tag'),
    # 文章标签列表
    path('note-<int:note_id>/', views.note, name='note'),
    # 学习笔记
    path('show-<int:article_id>/', views.show, name='show'),
    # 文章内容页
    path('section-<int:content_id>/', views.section, name='section'),
    # 笔记内容页
    path('timeAxis/', views.timeAxis, name='timeAxis'),
    # 时间轴
    path('messageBoard/', views.messageBoard, name='messageBoard'),
    # 留言板
    path('about/', views.about, name='about'),
    # 关于
    path('link/', views.link, name='link'),
    # 友情链接
    path('search', views.search, name='search'),
    # 搜索
    path('initApi', views.initApi, name='initApi'),
    # 初始化数据接口

    path('categoryPage', views.categoryPage, name='categoryPage'),
    # ajax文章分类分页
    path('tagPage', views.tagPage, name='tagPage'),
    # ajax标签分类分页
    path('indexPage', views.indexPage, name='indexPage'),
    # ajax首页流加载
    path('articleLike', views.articleLike, name='articleLike'),
    # ajax文章点赞
    path('articleCollection', views.articleCollection, name='articleCollection'),
    # ajax文章添加收藏
    path('deleteCollection', views.deleteCollection, name='deleteCollection'),
    # ajax文章取消收藏
    path('timeArticle', views.timeArticle, name='timeArticle'),
    # ajax时间轴文章列表
    path('postMessage', views.postMessage, name='postMessage'),
    # ajax发布留言
    path('likeMessage', views.likeMessage, name='likeMessage'),
    # ajax点赞留言
    path('delMessage', views.delMessage, name='delMessage'),
    # ajax删除留言
    path('postComment', views.postComment, name='postComment'),
    # ajax发布评论
    path('likeComment', views.likeComment, name='likeComment'),
    # ajax点赞评论
    path('delComment', views.delComment, name='delComment'),
    # ajax删除评论
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from blog import views
from django.views.static import serve
from myblog.settings import MEDIA_ROOT

urlpatterns = [
    re_path('media/(?P<path>.*)', serve, {'document_root': MEDIA_ROOT}, name='media_url'),
    # 媒体资源
    path('', views.index, name='index'),
    # 博客首页
    path('myblog_admin/', admin.site.urls),
    # admin管理页
    path('login/', include('social_django.urls', namespace='social')),
    # 第三方账户登录
    path('account/', include('account.urls', namespace='account')),
    # 个人中心
    path('blog/', include('blog.urls', namespace='blog')),
    # 博客前台
    path('management/', include('management.urls', namespace='management')),
    # 博客后台
    path('captcha', include('captcha.urls')),
    # 验证码
    path('sitemap/', views.siteMap, name='siteMap'),
    # 生成网站地图
]

templates/layui-mini/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>崔亮的博客</title>
    <meta name="keywords" content="layuimini,layui,layui模板,layui后台,后台模板,admin,admin模板,layui mini">
    <meta name="description"
          content="layuimini基于layui的轻量级前端后台管理框架，最简洁、易用的后台框架模板，面向所有层次的前后端程序,只需提供一个接口就直接初始化整个框架，无需复杂操作。">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta http-equiv="Access-Control-Allow-Origin" content="*">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'css/layui-mini.css' %}" media="all">
    <link rel="stylesheet" href="{% static 'layui-mini/lib/layui-v2.5.5/css/layui.css' %}" media="all">
    <link rel="stylesheet" href="{% static 'layui-mini/css/layuimini.css' %}" media="all">
    <link rel="stylesheet" href="{% static 'layui-mini/css/themes/default.css' %}" media="all">
    <link rel="stylesheet" href="{% static 'fontawesome-free-5.11.2-web/css/all.min.css' %}" media='all'/>
    <!--[if lt IE 9]>
    <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
    <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style id="layuimini-bg-color">
    </style>
</head>
<body class="layui-layout-body layuimini-all">
<div class="layui-layout layui-layout-admin">

    <div class="layui-header header">
        <div class="layui-logo layuimini-logo"></div>

        <div class="layuimini-header-content">
            <a>
                <div class="layuimini-tool"><i title="展开" class="fa fa-outdent" data-side-fold="1"></i></div>
            </a>

            <!--电脑端头部菜单-->
            <ul class="layui-nav layui-layout-left layuimini-header-menu layuimini-menu-header-pc layuimini-pc-show">

            </ul>

            <!--手机端头部菜单-->
            <ul class="layui-nav layui-layout-left layuimini-header-menu layuimini-mobile-show">
                <li class="layui-nav-item">
                    <a href="javascript:;"><i class="fa fa-list-ul"></i> 选择模块</a>
                    <dl class="layui-nav-child layuimini-menu-header-mobile">
                    </dl>
                </li>
            </ul>

            <ul class="layui-nav layui-layout-right">

                <li class="layui-nav-item" lay-unselect>
                    <a href="javascript:;" data-refresh="刷新"><i class="fa fa-sync-alt"></i></a>
                </li>
                <li class="layui-nav-item" lay-unselect>
                    <a href="javascript:;" data-clear="清理" class="layuimini-clear"><i class="fa fa-trash-alt"></i></a>
                </li>
                <li class="layui-nav-item mobile layui-hide-xs" lay-unselect>
                    <a href="javascript:;" data-check-screen="full"><i class="fa fa-arrows-alt"></i></a>
                </li>
                <li class="layui-nav-item layuimini-setting">
                    {% if userinfo %}
                        <a href="javascript:;">
                            <img src="{{ MEDIA_URL }}{{ userinfo.photo }}"
                                 class="layui-nav-img">{{ user.username | slice:"8" }}
                        </a>
                    {% else %}
                        <a href="javascript:;">
                            <img src="{{ MEDIA_URL }}{{ img.photo }}"
                                 class="layui-nav-img">{{ user.username | slice:"8" }}
                        </a>
                    {% endif %}
                    <dl class="layui-nav-child">
                        <dd>
                            <a href="javascript:;" layuimini-content-href="{% url 'account:changeInformation' %}"
                               data-title="修改信息"
                               data-icon="fa fa-gears">修改信息</a>
                        </dd>
                        <dd>
                            <a href="javascript:;" layuimini-content-href="{% url 'account:changePassword' %}"
                               data-title="修改密码"
                               data-icon="fa fa-gears">修改密码</a>
                        </dd>
                        <dd>
                            <hr>
                        </dd>
                        <dd>
                            <a href="javascript:;" class="login-out">退出登录</a>
                        </dd>
                    </dl>
                </li>
                <li class="layui-nav-item layuimini-select-bgcolor" lay-unselect>
                    <a href="javascript:;" data-bgcolor="配色方案"><i class="fa fa-ellipsis-v"></i></a>
                </li>
            </ul>
        </div>
    </div>

    <!--无限极左侧菜单-->
    <div class="layui-side layui-bg-black layuimini-menu-left">
    </div>

    <!--初始化加载层-->
    <div class="layuimini-loader">
        <div class="layuimini-loader-inner"></div>
    </div>

    <!--手机端遮罩层-->
    <div class="layuimini-make"></div>

    <!-- 移动导航 -->
    <div class="layuimini-site-mobile"><i class="layui-icon"></i></div>

    <div class="layui-body">

        <div class="layuimini-tab layui-tab-rollTool layui-tab" lay-filter="layuiminiTab" lay-allowclose="true">
            <ul class="layui-tab-title">
                <li class="layui-this" id="layuiminiHomeTabId" lay-id=""></li>
            </ul>
            <div class="layui-tab-control">
                <li class="layuimini-tab-roll-left layui-icon layui-icon-left"></li>
                <li class="layuimini-tab-roll-right layui-icon layui-icon-right"></li>
                <li class="layui-tab-tool layui-icon layui-icon-down">
                    <ul class="layui-nav close-box">
                        <li class="layui-nav-item">
                            <a href="javascript:;"><span class="layui-nav-more"></span></a>
                            <dl class="layui-nav-child">
                                <dd><a href="javascript:;" layuimini-tab-close="current">关 闭 当 前</a></dd>
                                <dd><a href="javascript:;" layuimini-tab-close="other">关 闭 其 他</a></dd>
                                <dd><a href="javascript:;" layuimini-tab-close="all">关 闭 全 部</a></dd>
                            </dl>
                        </li>
                    </ul>
                </li>
            </div>
            <div class="layui-tab-content">
                <div id="layuiminiHomeTabIframe" class="layui-tab-item layui-show"></div>
            </div>
        </div>

    </div>
</div>
<script src="{% static 'layui-mini/lib/layui-v2.5.5/layui.js' %}" charset="utf-8"></script>
<script src="{% static 'layui-mini/js/lay-config.js' %}" charset="utf-8"></script>
<script>
    layui.use(['jquery', 'layer', 'miniAdmin'], function () {
        var $ = layui.jquery,
            layer = layui.layer,
            miniAdmin = layui.miniAdmin;
        var options = {
            iniUrl: "{% url 'blog:initApi' %}?type=" + window.location.pathname,    // 初始化接口
            clearUrl: "{% static 'layui-mini/api/clear.json' %}", // 缓存清理接口
            urlHashLocation: true,      // 是否打开hash定位
            bgColorDefault: false,      // 主题默认配置
            multiModule: true,          // 是否开启多模块
            menuChildOpen: false,       // 是否默认展开菜单
            loadingTime: 0,             // 初始化加载时间
            pageAnim: true,             // iframe窗口动画
            maxTabNum: 20,              // 最大的tab打开数量
        };
        miniAdmin.render(options);

        $('.login-out').on("click", function () {
            layer.msg('退出登录成功')
            setTimeout(function () {
                window.location = '/account/logout';
            }, 1500);
        });
        // 第三方用户第一次登录，重载页面，获取头像昵称
        setTimeout(function () {
            var userinfo = '{{ userinfo }}'
            console.log(userinfo)
            if (userinfo == 'None') {
                location.reload();
            }else {
                return ;
            }
        }, 1000);
    });
</script>
</body>
</html>