account/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = "account"

urlpatterns = [
    path('loginRegister/', views.loginRegister, name='loginRegister'),
    # 登录注册页
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='logout'),
    # 注销
    path('forgetPassword/', views.forgetPassword, name='forgetPassword'),
    # 忘记密码

    path('', views.account, name='account'),
    # 个人中心模块
    path('personalCenter/', views.personalCenter, name='personalCenter'),
    # 个人中心首页
    path('changeInformation/', views.changeInformation, name='changeInformation'),
    # 修改信息
    path('changePassword/', views.changePassword, name='changePassword'),
    # 修改密码
    path('changeEmail/', views.changeEmail, name='changeEmail'),
    # 修改邮箱
    path('historyBrowse/', views.historyBrowse, name='historyBrowse'),
    # 浏览记录
    path('historyLike/', views.historyLike, name='historyLike'),
    # 收藏记录
    path('historyComment/', views.historyComment, name='historyComment'),
    # 评论记录
    path('historyLeave/', views.historyLeave, name='historyLeave'),
    # 留言记录

    path('tableData', views.tableData, name='tableData'),
    # ajax动态表格数据
    path('tableSearch', views.tableSearch, name='tableSearch'),
    # ajax动态表格搜索
    path('tableForm', views.tableForm, name='tableForm'),
    # ajax动态表格表单

    path('registerCheck', views.registerCheck, name='registerCheck'),
    # ajax用户注册信息验证
    path('imageUpload/', views.imageUpload, name='imageUpload'),
    # ajax图片上传接口(头像 文章封面)
    path('commentUpload/', views.commentUpload, name='commentUpload'),
    # ajax评论图片上传
    path('markdownUpload/', views.markdownUpload, name='markdownUpload'),
    # ajax markdown图片上传
    path('emailCode/', views.emailCode, name='emailCode'),
    # ajax获取邮件验证码
    path('checkEmailCode/', views.checkEmailCode, name='checkEmailCode'),
    # ajax校验邮件验证码
    path('bindEmail/', views.bindEmail, name='bindEmail'),
    # ajax绑定邮箱
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('category-<int:category_id>/', views.category, name='category'),
    # 文章分类列表
    path('tag-<int:tag_id>/', views.tag, name='tag'),
    # 文章标签列表
    path('note-<int:note_id>/', views.note, name='note'),
    # 学习笔记
    path('show-<int:article_id>/', views.show, name='show'),
    # 文章内容页
    path('section-<int:content_id>/', views.section, name='section'),
    # 笔记内容页
    path('timeAxis/', views.timeAxis, name='timeAxis'),
    # 时间轴
    path('messageBoard/', views.messageBoard, name='messageBoard'),
    # 留言板
    path('about/', views.about, name='about'),
    # 关于
    path('link/', views.link, name='link'),
    # 友情链接
    path('search', views.search, name='search'),
    # 搜索
    path('initApi', views.initApi, name='initApi'),
    # 初始化数据接口

    path('categoryPage', views.categoryPage, name='categoryPage'),
    # ajax文章分类分页
    path('tagPage', views.tagPage, name='tagPage'),
    # ajax标签分类分页
    path('indexPage', views.indexPage, name='indexPage'),
    # ajax首页流加载
    path('articleLike', views.articleLike, name='articleLike'),
    # ajax文章点赞
    path('articleCollection', views.articleCollection, name='articleCollection'),
    # ajax文章添加收藏
    path('deleteCollection', views.deleteCollection, name='deleteCollection'),
    # ajax文章取消收藏
    path('timeArticle', views.timeArticle, name='timeArticle'),
    # ajax时间轴文章列表
    path('postMessage', views.postMessage, name='postMessage'),
    # ajax发布留言
    path('likeMessage', views.likeMessage, name='likeMessage'),
    # ajax点赞留言
    path('delMessage', views.delMessage, name='delMessage'),
    # ajax删除留言
    path('postComment', views.postComment, name='postComment'),
    # ajax发布评论
    path('likeComment', views.likeComment, name='likeComment'),
    # ajax点赞评论
    path('delComment', views.delComment, name='delComment'),
    # ajax删除评论
]

management/urls.py
from django.urls import path
from . import views

app_name = "management"

urlpatterns = [
    path('', views.management, name='management'),
    # 后台管理模块
    path('dashboard/', views.dashboard, name='dashboard'),
    # 后台管理dashboard
    path('articleAdd/', views.articleAdd, name='articleAdd'),
    # 新增文章
    path('articleList/', views.articleList, name='articleList'),
    # 文章列表
    path('articleCategory/', views.articleCategory, name='articleCategory'),
    # 文章分类
    path('articleTag/', views.articleTag, name='articleTag'),
    # 文章标签
    path('articleComment/', views.articleComment, name='articleComment'),
    # 文章评论
    path('sectionNote/', views.sectionNote, name='sectionNote'),
    # 笔记名称
    path('sectionList/', views.sectionList, name='sectionList'),
    # 笔记列表
    path('sectionAdd/', views.sectionAdd, name='sectionAdd'),
    # 新增笔记内容
    path('sectionComment/', views.sectionComment, name='sectionComment'),
    # 笔记评论
    path('sectionCatalog/', views.sectionCatalog, name='sectionCatalog'),
    # 笔记目录编排
    path('websiteLeaveMessage/', views.websiteLeaveMessage, name='websiteLeaveMessage'),
    # 网站留言
    path('websiteCarousel/', views.websiteCarousel, name='websiteCarousel'),
    # 网站轮播图
    path('carouselAdd/', views.carouselAdd, name='carouselAdd'),
    # 新增轮播图
    path('websiteLink/', views.websiteLink, name='websiteLink'),
    # 网站友情链接
    path('linkAdd/', views.linkAdd, name='linkAdd'),
    # 新增友情链接
    path('websiteAbout/', views.websiteAbout, name='websiteAbout'),
    # 网站关于
    path('websiteConfig/', views.websiteConfig, name='websiteConfig'),
    # 网站配置
    path('BloggerInfo/', views.BloggerInfo, name='BloggerInfo'),
    # 博主信息
    path('managementUser/', views.managementUser, name='managementUser'),
    # 用户管理

    path('coverUpload/', views.coverUpload, name='coverUpload'),
    # ajax文章封面图片上传
    path('articleDel/', views.articleDel, name='articleDel'),
    # ajax删除文章
    path('articleEdit-<int:article_id>/', views.articleEdit, name='articleEdit'),
    # ajax修改文章
    path('categoryDel/', views.categoryDel, name='categoryDel'),
    # ajax删除分类
    path('categoryEdit/', views.categoryEdit, name='categoryEdit'),
    # ajax修改分类
    path('categoryAdd/', views.categoryAdd, name='categoryAdd'),
    # ajax新增分类
    path('tagAdd/', views.tagAdd, name='tagAdd'),
    # ajax新增标签
    path('tagEdit/', views.tagEdit, name='tagEdit'),
    # ajax修改标签
    path('tagDel/', views.tagDel, name='tagDel'),
    # ajax删除标签
    path('noteAdd/', views.noteAdd, name='noteAdd'),
    # ajax新增笔记名称
    path('noteDel/', views.noteDel, name='noteDel'),
    # ajax删除笔记名称
    path('noteEdit/', views.noteEdit, name='noteEdit'),
    # ajax修改笔记名称
    path('sectionDel/', views.sectionDel, name='sectionDel'),
    # ajax删除笔记内容
    path('sectionEdit-<int:section_id>/', views.sectionEdit, name='sectionEdit'),
    # ajax修改笔记内容
    path('catalogEdit/', views.catalogEdit, name='catalogEdit'),
    # ajax获取章节名称
    path('carouselDel/', views.carouselDel, name='carouselDel'),
    # ajax删除轮播图
    path('carouselEdit-<int:carousel_id>/', views.carouselEdit, name='carouselEdit'),
    # ajax编辑轮播图
    path('linkDel/', views.linkDel, name='linkDel'),
    # ajax删除友链
    path('linkEdit-<int:link_id>/', views.linkEdit, name='carouselEdit'),
    # ajax编辑友链
    path('userDel/', views.userDel, name='userDel'),
    # ajax删除用户
    path('echartsData', views.echartsData, name='echartsData'),
    # ajax echarts数据接口
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from blog import views
from django.views.static import serve
from myblog.settings import MEDIA_ROOT

urlpatterns = [
    re_path('media/(?P<path>.*)', serve, {'document_root': MEDIA_ROOT}, name='media_url'),
    # 媒体资源
    path('', views.index, name='index'),
    # 博客首页
    path('myblog_admin/', admin.site.urls),
    # admin管理页
    path('login/', include('social_django.urls', namespace='social')),
    # 第三方账户登录
    path('account/', include('account.urls', namespace='account')),
    # 个人中心
    path('blog/', include('blog.urls', namespace='blog')),
    # 博客前台
    path('management/', include('management.urls', namespace='management')),
    # 博客后台
    path('captcha', include('captcha.urls')),
    # 验证码
    path('sitemap/', views.siteMap, name='siteMap'),
    # 生成网站地图
]

templates/base-blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="keywords" content={{ site.keywords }}>
    <meta name="description" content={{ site.descript }}>
    <meta name='referrer' content="no-referrer-when-downgrade">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}" media="all">
    <link rel="stylesheet" href="{% static 'css/public.css' %}">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome-free-5.11.2-web/css/all.min.css' %}" media='all'/>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"/>
    <script src="{% static 'layui/layui.js' %}" charset="utf-8"></script>
    <script src="{% static 'jquery-3.5.1/jquery-3.5.1.min.js' %}" charset="utf-8"></script>
    {% block link %}{% endblock %}
    {#头条搜索#}
    <meta name="bytedance-verification-code" content="RAweXW/Li30Fs1KVWfQJ" />
    {#必应搜索#}
    <meta name="msvalidate.01" content="0B706DC4E27F508AA5889A273F759EB8" />
    {#谷歌搜索#}
    <meta name="google-site-verification" content="GtNO79LEUpHXJTZULN42OgdLYvzWzs04O_l_waRDqhE" />
    {#360搜索#}
    <meta name="360-site-verification" content="03c4710b08af2b2fec5bf3a45c256f69" />
    {#搜狗搜索#}
    <meta name="sogou_site_verification" content="ZFOpMx7y0J"/>
    {#百度统计#}
    <script>
        var _hmt = _hmt || [];
        (function () {
            var hm = document.createElement("script");
            hm.src = "https://hm.baidu.com/hm.js?5abb8d046dd1dd0d2ff4094f445b3079";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();
    </script>
</head>
<body>
{#头部#}
<!--电脑版导航栏-->
<nav class="nav-fixed">
    <div class="nav-left">
        <span><a class="nav-show-btn"><i></i></a></span>
        <span class="logo">
            <h1>
                <a href="/" title="崔亮的博客">崔亮的博客</a>
            </h1>
        </span>
    </div>
    <ul class="layui-nav">
        <li class="layui-nav-item layui-hide-xs nav1"><a href="/">首页</a></li>
        <li class="layui-nav-item layui-hide-xs nav2">
            <a href="javascript:">文章分类</a>
            <dl class="layui-nav-child">
                {% for category in categorys %}
                    <dd id="category-{{ category.id }}"><a
                            href="/blog/category-{{ category.id }}">{{ category.name }}</a></dd>
                {% endfor %}
            </dl>
        </li>
        <li class="layui-nav-item layui-hide-xs nav3">
            <a href="javascript:">学习笔记</a>
            <dl class="layui-nav-child">
                {% for note in notes %}
                    <dd id="note-{{ note.id }}"><a href="/blog/note-{{ note.id }}">{{ note.name }}</a></dd>
                {% endfor %}
            </dl>
        </li>
        <li class="layui-nav-item layui-hide-xs nav4">
            <a href="{% url 'blog:timeAxis' %}">时间轴</a>
        </li>
        <li class="layui-nav-item layui-hide-xs nav5">
            <a href="{% url 'blog:messageBoard' %}">留言板</a>
        </li>
        <li class="layui-nav-item layui-hide-xs nav6">
            <a href="{% url 'blog:about' %}">关于</a>
        </li>
        <li class="layui-nav-item nav-user-online layui-hide-xs nav7">
            {% if user.is_authenticated %}
                {#                    用户已登录#}
                {% if userinfo %}
                    <a href="javascript:;"><img lay-src="{{ MEDIA_URL }}{{ userinfo.photo }}"
                                                class="layui-nav-img">{{ user.username | slice:"8" }}
                {% else %}
                    <a href="javascript:;"><img lay-src="{{ MEDIA_URL }}{{ img.photo }}"
                                                class="layui-nav-img">{{ user.username | slice:"8" }}
                {% endif %}
            </a>
                <dl class="layui-nav-child">
                    <dd><a href="{% url 'account:account' %}">个人中心</a></dd>
                    {% if user.is_superuser %}
                        <dd><a href="{% url 'management:management' %}">网站管理</a></dd>
                    {% endif %}
                    <dd><a href="{% url 'account:logout' %}">退出登录</a></dd>
                </dl>
            {% else %}
                {#                    用户未登录#}
                <span>
                        <a class="nav-user" href="{% url 'account:loginRegister' %}"><i
                                class="layui-icon layui-icon-friends"></i></a>
                    </span>
            {% endif %}
        </li>
        <li class="nav-rignt">
            <span><a class="nav-search" href="#"><i></i></a></span>
        </li>
    </ul>
</nav>
<!--滑动搜索框特效-->
<div class="search-box">
    <div class="search-form">
        <form name="search" class="layui-form" method="get" action="{% url 'blog:search' %}">
            {% csrf_token %}
            {{ search_form.key }}
            <input type="submit" name="submit" lay-submit="" value="搜索" id="submit">
        </form>
    </div>
</div>
<!--手机版侧边栏-->
<div class="layui-side layui-side-menu side-close">
    <div class="layui-side-scroll">
        <ul class="layui-nav layui-nav-tree" id="LAY-system-side-menu" style="height: 100%">
            <li data-name="home" class="layui-nav-item layui-nav-itemed side-home nav1">
                <a href="/">
                    <i class="layui-icon layui-icon-home"></i>
                    <cite>首页</cite>
                </a>
            </li>
            <li data-name="component" class="layui-nav-item">
                <a href="javascript:">
                    <i class="layui-icon layui-icon-component"></i>
                    <cite>文章分类</cite>
                    <span class="layui-nav-more"></span></a>
                <dl class="layui-nav-child">
                    {% for category in categorys %}
                        <dd id="m-category-{{ category.id }}"><a
                                href="/blog/category-{{ category.id }}">{{ category.name }}</a></dd>
                    {% endfor %}
                </dl>
            </li>
            <li data-name="template" class="layui-nav-item nav3">
                <a href="javascript:">
                    <i class="layui-icon layui-icon-template"></i>
                    <cite>学习笔记</cite>
                    <span class="layui-nav-more"></span></a>
                    <dl class="layui-nav-child">
                    {% for note in notes %}
                        <dd id="m-note-{{ note.id }}"><a href="/blog/note-{{ note.id }}">{{ note.name }}</a></dd>
                    {% endfor %}
                </dl>
            </li>
            <li data-name="senior" class="layui-nav-item nav4">
                <a href="{% url 'blog:timeAxis' %}">
                    <i class="layui-icon layui-icon-senior"></i>
                    <cite>时间轴</cite></a>
            </li>
            <li data-name="user" class="layui-nav-item nav5">
                <a href="{% url 'blog:messageBoard' %}">
                    <i class="layui-icon layui-icon-user"></i>
                    <cite>留言板</cite></a>
            </li>
            <li data-name="get" class="layui-nav-item nav6">
                <a href="{% url 'blog:about' %}">
                    <i class="layui-icon layui-icon-auz"></i>
                    <cite>关于</cite>
                </a>
            </li>
            {% if user.is_authenticated %}
                <li data-name="component" class="layui-nav-item nav7">
                    <a href="javascript:">
                        <i class="layui-icon layui-icon-friends"></i>
                        <cite>{{ user.username | slice:"10" }}</cite>
                        <span class="layui-nav-more"></span></a>
                    <dl class="layui-nav-child">
                        <dd data-name="button">
                            <a href="{% url 'account:account' %}">个人中心</a>
                        </dd>
                        {% if user.is_superuser %}
                            <dd data-name="nav">
                                <a href="{% url 'management:management' %}">网站管理</a>
                            </dd>
                        {% endif %}
                        <dd data-name="button">
                            <a href="{% url 'account:logout' %}">退出登录</a>
                        </dd>
                    </dl>
                </li>
            {% else %}
                <li data-name="component" class="layui-nav-item nav7">
                    <a href="{% url 'account:loginRegister' %}">
                        <i class="layui-icon layui-icon-friends"></i>
                        <cite>登录&注册</cite>
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
</div>
{#正文#}
{% block content %}

{% endblock %}
{#底部#}
<!--回到顶部按钮-->
<div id="back-top" class="back-top suspend"><a href="javascript:;"><i class="layui-icon layui-icon-top"></i></a></div>
<footer>
    <div class="footer">
        <span><p>{{ site.copyright }}</p></span>
        <p>|</p>
        <span><a href="https://beian.miit.gov.cn/">陇ICP备19001718号</a></span>
        <p>|</p>
        <span><a
                href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11011202002337">京公安备11011202002337号</a></span>
        <p>|</p>
        <span><a href="{% url 'blog:link' %}">友情链接</a></span>
        <p>|</p>
        <span><p>Powered by Django</p></span>
    </div>
</footer>
{#js部分#}

<script>
    // 日期显示为几天前
    layui.config({
        version: true,
        base: "{% static 'timeago/' %}"
    }).extend({
        timeago: 'timeago'
    }).use(['timeago', 'layer'], function () {
        var $ = layui.jquery;
        var timeago = layui.timeago;
        var layer = layui.layer;
        timeago.render($('.timeago'));
    });
    // ajax加载动画
    var load
    $(document).on('ajaxStart', function () {
        load = layer.load();
    })
    $(document).on('ajaxComplete', function () {
        layer.close(load);
    })
    //导航的hover效果、二级菜单等功能，需要依赖element模块
    layui.use('element', function () {
        var element = layui.element;
        //监听导航点击
        element.on('nav(demo)', function (elem) {
            //console.log(elem)
            layer.msg(elem.text());
        });
    });
    // 手机侧边栏
    $('.nav-show-btn').on("click", function () {
        $('.nav-show-btn').toggleClass('nav-close-btn');
        $('.side-close').toggleClass('side-show');
        $('.page-main').toggleClass('page-main-side');
        $('.logo').toggleClass('logo-side');
    });
    // 下拉搜索框
    $('.nav-search').on("click", function () {
        setTimeout(function () {
            $('.nav-search').toggleClass('nav-search-close');
            $('.search-box').toggleClass('search-box-show');
            $('.search-form').toggle();
        }, 500)
    });
    // 导航栏吸顶效果
    $(document).ready(function () {
        var p = 0;
        t = 0;
        $(window).scroll(function () {
            p = $(this).scrollTop();
            if (t < p) {
                $('.nav-fixed').stop().slideUp(500);
            } else {
                $('.nav-fixed').stop().slideDown(500);
            }
            t = p;
        })
    })

    /*判断当在第一屏的时候，回到顶部按钮的时候隐藏*/
    $(window).scroll(function () {
        var scroll_len = $(window).scrollTop();
        if (scroll_len > 120) {
            $('#back-top').stop().fadeIn(1000);
        } else {
            $('#back-top').stop().fadeOut(1000);
        }
    });
    $('#back-top').click(function (e) {
        $("body,html").animate({scrollTop: 0}, 1000);
    })

    // 图片懒加载
    layui.use('flow', function () {
        var flow = layui.flow;
        //当你执行这样一个方法时，即对页面中的全部带有lay-src的img元素开启了懒加载（当然你也可以指定相关img）
        flow.lazyimg();
    });
</script>
{% block js %}

{% endblock %}
</body>
</html>

templates/email.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <title>Document</title>

<body style="background-color: #ebedf0;margin: 0;padding: 0">
<div id="content" style="width: 75%;margin: 10% auto;background-color: white;border-radius: 10px;box-shadow: 0 0 15px 1px rgba(0, 0, 0, 0.4);">
    <div style="text-align: center;background-color: #ecf0f1;height: 80px">
        <h2 style="margin: 0 auto;line-height: 80px;">【崔亮的博客】验证码</h2>
    </div>
    <div style="padding: 0 20px;">
        <p style="font-weight: bold">尊敬的星空的77：您好！</p>
        <p style="text-indent:2em;font-weight: bold">您正在进行
            <span style="color: #e74c3c">注册账号</span>操作，请在验证码输入框输入：
            <span style="color: #e74c3c;font-weight: bold;font-size: 40px">123421</span>，以完成操作，验证码有效期为3分钟。
        </p>
        <br>
        <p style="color: #bdc3c7;text-indent:2em">注意：此操作可能会对您的账号进行邮箱绑定、修改密码、重置密码操作。
            如非本人操作，请及时登录并修改密码以保证账户安全，请勿泄露此验证码！</p>
    </div>
    <div style="background-color: #ecf0f1;padding: 20px;">
        <p style="color: #bdc3c7;text-indent:2em;margin: 0 auto;line-height: 30px">您会收到这封邮件，是由于在
            <a href="https://www.cuiliangblog.cn" style="text-decoration: none">崔亮的博客</a>
            进行了新用户注册或修改密码、重置密码操作。如果您并没有访问过
            <a href="https://www.cuiliangblog.cn" style="text-decoration: none">崔亮的博客</a>
            ，或没有进行上述操作， 请忽略这封邮件！
        </p>
    </div>
</div>
</body>

</html>

templates/layui.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="shortcut icon" href="../static/images/favicon.ico"/>
    <link rel="stylesheet" href="../static/layui-mini/lib/layui-v2.5.5/css/layui.css" media="all">
    <link rel="stylesheet" href="../static/layui-mini/css/public.css" media="all">
</head>
<div class="eletree"></div>
<body>
<div>
    <div class="layui-form-item">
        <label class="layui-form-label">邮箱号:</label>
        <div class="layui-input-inline">
            <input type="text" name="title" lay-verify="title" autocomplete="off" placeholder="请输入邮箱号"
                   class="layui-input">
        </div>
        <button type="button" class="layui-btn layui-btn-normal" id="send_btn">发送验证码</button>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">验证码:</label>
        <div class="layui-input-inline">
            <input type="text" name="title" lay-verify="title" autocomplete="off" placeholder="请输入验证码"
                   class="layui-input">
        </div>
    </div>
</div>
<table class="layui-table" lay-even="" lay-skin="nob">
                        <thead>
                        <tr>
                            <th>浏览文章数：</th>
                            <th>{{ view_count }}篇</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>收藏文章数：</td>
                            <td>{{ like_count }}篇</td>
                        </tr>

                        <tr>
                            <td>文章评论数：</td>
                            <td>{{ comment_count }}条</td>
                        </tr>
                        <tr>
                            <td>浏览笔记数：</td>
                            <td>{{ view_count }}篇</td>
                        </tr>
                        <tr>
                            <td>收藏笔记数：</td>
                            <td>{{ like_count }}篇</td>
                        </tr>
                        <tr>
                            <td>笔记评论数：</td>
                            <td>{{ like_count }}篇</td>
                        </tr>
                        <tr>
                            <td>发表留言数：</td>
                            <td>{{ leave_count }}条</td>
                        </tr>
                        </tbody>
                    </table>
<script src="../static/layui-mini/lib/layui-v2.5.5/layui.js" charset="utf-8"></script>
<script src="../static/layui-mini/js/lay-config.js" charset="utf-8"></script>
<script>
    layui.use(['form', 'eleTree'], function () {
        var form = layui.form
            , layer = layui.layer
            , eleTree = layui.eleTree;
        layer.msg('只想弱弱提示');
    });
</script>
</body>
</html>